<footer class="footer-distributed">

    <div class="footer-right">

        <a target="_blank" href="https://www.instagram.com/n00ka_studio/"><i class="ri-instagram-line"></i></i></a>
        <a target="_blank" href="https://www.tiktok.com/@n00ka7"><i class="ri-tiktok-fill"></i></a>
        <a target="_blank" href="https://www.linkedin.com/company/n00ka/"><i class="ri-linkedin-box-fill"></i></a>

    </div>

    <div class="footer-left">

        <p class="footer-links">
            <a href="index.php">Accueil</a>

            <a href="contact.php">Contact</a>

            <a href="terms.php">Terms</a>
        </p>

        <div style="display: flex; margin-top: 25px;">
            <p style="text-align: start; width: 50%">N00ka Studio &copy; 2025</p>

            <p style="text-align: end; width: 50%">Site créé par <a id="tyrolium" target="_blank" href="https://tyrolium.fr">Tyrolium</a></p>
        </div>

    </div>

</footer>

<style>
</style>