<footer class="footer-distributed">

    <div class="footer-right">

        <a target="_blank" href="https://www.instagram.com/n00ka_studio/"><i class="ri-instagram-line"></i></i></a>
        <a target="_blank" href="https://www.tiktok.com/@n00ka7"><i class="ri-tiktok-fill"></i></a>
        <a target="_blank" href="https://www.linkedin.com/company/n00ka/"><i class="ri-linkedin-box-fill"></i></a>

    </div>

    <div class="footer-left">

        <p class="footer-links">
            <a class="link-1" href="index.php">Accueil</a>

            <a href="#">Contact</a>

            <a href="terms.php">Terms</a>
        </p>

        <div style="display: flex; margin-top: 25px;">
            <p style="text-align: start; width: 50%">N00ka Studio &copy; 2025</p>

            <p style="text-align: end; width: 50%">Site créé par <a id="tyrolium" target="_blank" href="https://tyrolium.fr">Tyrolium</a></p>
        </div>

    </div>

</footer>

<style>
    .footer-distributed {
        background-color: #292c2f;
        box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
        box-sizing: border-box;
        width: 100%;
        text-align: left;
        font: normal 16px sans-serif;
        padding: 45px 50px;
    }

    .footer-distributed .footer-left p {
        color: #8f9296;
        font-size: 14px;
        margin: 0;
    }
    /* Footer links */

    .footer-distributed p.footer-links {
        font-size: 18px;
        font-weight: bold;
        color: #ffffff;
        padding: 0;
        transition: ease .25s;
        margin: 8px 0 10px;
    }

    .footer-distributed p.footer-links a {
        display: inline-block;
        line-height: 1.8;
        text-decoration: none;
        color: inherit;
        transition: ease .25s;
    }

    .footer-distributed .footer-links a:before {
        content: "·";
        font-size: 20px;
        left: 0;
        color: #fff;
        display: inline-block;
        padding-right: 5px;
    }

    .footer-distributed .footer-links .link-1:before {
        content: none;
    }

    .footer-distributed .footer-right {
        float: right;
        margin-top: 6px;
        max-width: 180px;
    }

    .footer-distributed .footer-right a {
        display: inline-block;
        width: 35px;
        height: 35px;
        background-color: #33383b;
        border-radius: 2px;
        font-size: 20px;
        color: #ffffff;
        text-align: center;
        line-height: 35px;
        margin-left: 3px;
        transition:all .25s;
        text-decoration: none;
    }

    .footer-distributed .footer-right a:hover{transform:scale(1.1); -webkit-transform:scale(1.1);}

    .footer-distributed p.footer-links a:hover{text-decoration:underline;}

    /* Media Queries */

    @media (max-width: 600px) {
        .footer-distributed .footer-left, .footer-distributed .footer-right {
            text-align: center;
        }
        .footer-distributed .footer-right {
            float: none;
            margin: 0 auto 20px;
        }
        .footer-distributed .footer-left p.footer-links {
            line-height: 1.8;
        }
    }

    #tyrolium {
        color: unset;


    }

    #tyrolium:hover {
        color: #3a3aff;
    }

</style>