<header>
    <div class="sign">
        <div class="logo"></div>
    </div>
</header>

<style>

    header{
        width: 100%;
        height: 900px;
        background-image: url("file_assets/wood.jpg");
        background-position: center;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        padding-bottom: 40px;

        display: flex; /* Active le modèle Flexbox pour le header */
        justify-content: center; /* Centre horizontalement les éléments enfants */
        align-items: center; /* Centre verticalement les éléments enfants */

        div.sign{
            width: 600px;
            height: 327px;
            background-color: white;
            border-radius: 30px;
        }

        div.logo{
            width: 100%;
            height: 100%;
            background-image: url("file_assets/logo.png");
            background-size: 100% 100%;
        }

    }





</style>