<header>
    <div class="sign">
        <div class="logo"></div>
    </div>
</header>

<style>

    header{
        width: 100%;
        height: 600px;
        background-image: url("file_assets/wood.jpg");
        background-position: center;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;

        div.sign{
            width: 500px;
            height: 200px;
            background-color: white;
            border-radius: 30px;
        }

        div.logo{
            width: 100%;
            height: 100%;
            background-image: url("file_assets/logo.png");
            background-size: 100% 100%;
        }

    }





</style>